### ISSUE TITLE
Ambilight centred incorrectly

### ISSUE THREAD

**Issue by Dj3DX** [nicojeske/RazerAmbilight#18]
It might be because I have a 1440p main display and a 1080p secondary but placing a small window in the middle of the screen makes the white box span from the centre of the keyboard all the way to the right, even though there should be the background showing on both sides if you get what I mean. Maybe a way to horizontally shift it?

**Comment by nicojeske** [comment]
Normally the program gets the resolution of your primary screen via an api call to the OS. In this context what you describe should not be possible. The only thing that comes in my mind is that you have selected the 1080p monitor as your primary screen in Windows. 
If this is not the problem I will add more logging to the app and release an update after which you would have to send me the log, so that I could further investigate this issue.

**Comment by nicojeske** [comment]
Please update to version 2.0. that should propably fix the problem. If not, feel free to open a new issue.
